/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerTeman;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import model.ModelTeman;
import util.Koneksi;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class ViewTeman extends javax.swing.JFrame {
    
    Koneksi koneksi = new Koneksi();
    ControllerTeman ct = new ControllerTeman();
    ModelTeman mt = new ModelTeman();

    /**
     * Creates new form ViewTeman
     */
    public ViewTeman() {
        initComponents();
        setLocationRelativeTo(null);
        datatable();
        
    }
    
    private void baru(){
        
    }
    
    private void datatable(){
        koneksi.koneksiDatabase();
        
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("id");
        tabel.addColumn("nama");
        tabel.addColumn("nope");
        tabel.addColumn("email");
        jTable1.setModel(tabel);
        
        try {
            String sql = "select * from tbl_teman";
            ResultSet res = koneksi.state.executeQuery(sql);
            while (res.next()){
                tabel.addRow(new Object []{
                    res.getString("id"),
                    res.getString("nama"),
                    res.getString("nope"),
                    res.getString("email")
                                
                }); 
         
            }
        } catch (SQLException e) {
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jT_email = new javax.swing.JTextField();
        jT_id = new javax.swing.JTextField();
        jT_nama = new javax.swing.JTextField();
        jT_nope = new javax.swing.JTextField();
        Btn_tutup = new javax.swing.JButton();
        Btn_baru = new javax.swing.JButton();
        Btn_simpan = new javax.swing.JButton();
        Btn_bersih = new javax.swing.JButton();
        Btn_ubah = new javax.swing.JButton();
        Btn_hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Email :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel2.setText("id :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel3.setText("Nama :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel4.setText("No. Hp :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
        getContentPane().add(jT_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 160, -1));
        getContentPane().add(jT_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 100, -1));
        getContentPane().add(jT_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 160, -1));
        getContentPane().add(jT_nope, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 160, -1));

        Btn_tutup.setText("Tutup");
        getContentPane().add(Btn_tutup, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 70, -1));

        Btn_baru.setText("Baru");
        getContentPane().add(Btn_baru, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 70, -1));

        Btn_simpan.setText("Simpan");
        Btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_simpanActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        Btn_bersih.setText("Bersih");
        getContentPane().add(Btn_bersih, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 70, -1));

        Btn_ubah.setText("Ubah");
        getContentPane().add(Btn_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 70, -1));

        Btn_hapus.setText("Hapus");
        getContentPane().add(Btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 70, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 480, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void Btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_simpanActionPerformed
        // TODO add your handling code here:
        try {
            String nama = jT_nama.getText().trim();
            String nope = jT_nope.getText().trim();
            String email = jT_email.getText().trim();
            mt.setNama(nama);
            mt.setNope(nope);
            mt.setEmail(email);
            ct.simpandata(mt);
            datatable();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_Btn_simpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTeman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_baru;
    private javax.swing.JButton Btn_bersih;
    private javax.swing.JButton Btn_hapus;
    private javax.swing.JButton Btn_simpan;
    private javax.swing.JButton Btn_tutup;
    private javax.swing.JButton Btn_ubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jT_email;
    private javax.swing.JTextField jT_id;
    private javax.swing.JTextField jT_nama;
    private javax.swing.JTextField jT_nope;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
